name: cli
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cbl: ^2.0.0
  cbl_dart: ^2.0.0
  cli_repl: ^0.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
